const thoughts = [
    "im gunna die right now",
    "i cant believe u fell for it",
    "u will never forget me",
    "i hope i make u fucking sick",
    "i will never speak again",
    "i will destroy myself for you", 
    "do you love me",
    "im ripping my face off and",
    "putting it in a blender",
    "im ripping my stomach out with my bare hands",
    "dont stop it hurts",
    "skin is meant to be torn",
    "one hammer to the head please",
    "a little mess is no big deal",
    "u are everything i have ever dreamed of",
    "i deserve to be abused",
    "im scared of my own brain",
    "i never deserved what happened to me",
    "everyone knows my secret",
    "my mother was just doing her best",
    "i am incapable of loving",
    "im leaving everyone who loves me",
    "if u love me then u dont know me",
    "u mean its all out of my control?",
    "this is it? fuck",
    "dont piss me off",
    "i am overflowing with love",
    "i cannot wait to nurture my daughter",
    "i am perfectly lovable",
    "i am divine.",
    "i will rip ur heart out and eat it",
    "loving u makes me sick",
    "this soup tastes like its all worth it",
    "i am nothing without female friendships",
    "i need a fucking cigarette",
    "they will always betray you",
    "you should have seen it",
    "dont let them fool you this time",
    "i wish my ass was fatter",
    "the answer is 3",
    "u see me as an object? what a relief.",
    "faking that u didnt orgasm is feminine",
    "i think i would rather die than eat",
    "u are the last woman i will ever kiss.",
    "but the bottle was always there",
    "i'm not even bisexual",
    "ur not queer enough",
    "ur fat ass wouldn't last a day in my culture",
    "pick a side",
    "stay away im dirty and will never be clean",
    "god i really need a fucking cigarette",
    "when my dad dies i'll regret ignoring him",
    "that girl who used to purge me",
    "i guess i love narcissists",
    "i should've picked the other guy",
    "ur new girlfriend looks just like me",
    "i'm not enough to be public",
    "shut the fuck up",
    "ur so fucking stupid",
    "shutupshutupshutupshutthefuckupIMBEGGING",
    "ur being UGLY",
    "that was not very feminine of u",
    "can u be more fucking ladylike",
    "no man is gunna want someone like you",
    "i dont give a fuck about what men want",
    "abolish men please",
    "the government is microchipping me via iud",
    "theyre listening shut the fuck up",
    "you are never truly alone",
    "everyone will find out your secret",
    "you look beautiful without makeup",
    "your skin is glowing",
    "i jumped in front of a train when i was 16",
    "my mom stabbed herself in front of me",
    "this sunny day is making me suffocate",
    "you are suffocating me",
    "are you cheating on me rn or tmo?",
    "i'm in love with your ex",
    "you mean i cant fix someone else",
    "i have no purpose if i'm not fixing someone",
    "i am enough. just as i am in this moment.",
    "your femininity is effortless",
    "i don't want to breathe",
    "what if i cant breathe",
    "you're not choking me hard enough",
    "can you grab the knife next time?",
    "can you just be fucking normal",
    "i love my own company",
    "cilantro ruins everything",
    "chop up another line",
    "i miss your drugs",
    "i need to text her back",
    "i havent texted him back",
    "i'm scared of you", 
    "these are all lies",
    "i would never lie",
    "i'm fucking confused",
    "i have disowned you mentally",
    "these have nothing to do with me",
    "am i being defensive?",
    "i hope he sees this",
    "how embarassing am i",
    "i will never stop loving you",
    "do i scare you",
    "who will run away first",
    "im running away",
    "do you still love me",
    "its ok i love myself",
    "oh my fucking god",
    "none of this is true",
    "none of this is about you",
    "my tweets are not about you",
    "the least intersting thing about me",
    "you're boring",
    "i'm bored",
    "self sabotage tn queen?",
    "dating men is a nightmare",
    "faking an ed is weird",
    "he asekd me what tribe i'm from",
    "emotional support git branch",
    "code reviews r too intimate",
    "this peach is better than 2019",
    "i want to play mah jong",
    "i need to get my tattoos removed",
    "i have a peeing juice box tattood",
    "i want your babies",
    "my feelings don't matter anyway",
    "can we talk about 2019 (no)",
    "ur a loser with a loser bf",
    "i got the ick for you and FOUGHT",
    "white ppl ate with tool",
    "size does matter",
    "LSD permanently damaged me",
    "i forgot sandwiches exist",
    "eating an apple off the bone",
    "will anyone ever write me a poem",
    "ill allow the men who suck toes",
    "you are so cool",
    "i am the coolest person i know",
    "where did all my money go",
    "all u need to know is cap venus",
    "i like girls",
    "who the fuck is she",
    "i got a glock in my rari",
    "what were u going to say?",
    "fuck spotify shuffle",
    "he lowkey doin it for me",
    "clubbing in nyc is my only chance",
    "normalize secrets",
    "why u got 4 github followers",
    "let me speak",
    "stop inturrupting me",
    "russian cream backwood",
    "ur my nightmare blunt rotation",
    "why did he stop taking pictures of me",
    "im ashamed to be in love",
    "my man is in love w his barber",
    "she said were made of the same stardust",
    "how many bodies u got",
    "im only gay for the vibes",
    "relationship or community service",
    "what did i do to u",
    "i dont got shit to say",
    "no one sucks toes these days",
    "i owe my life to my sister",
    "dont believe anything i say",
    "dating u is my self harm",
    "never change",
    "you are absolutely perfect",
    "i am precious",
    "life is beautiful",
    "life is worth living",
    "birds chirping in the warm breeze",
    "falling in love is beautiful",
    "i am previous",
    "i am dearly loved",
    "you are absolutely breathtaking",
    "i am lucky to know you",
    "我不是中國人",
    "我是一個恥辱",
    "我翻譯這個是因為我是個騙子",
    "我愛你",
    "我永遠不會愛你",
    "i will find you in every life",
    "你需要減肥",
    "我恨你父親",
    "從來沒有孩子",
    "he so fine",
    "pearl in the palm",
    "perform for me",
    "please our guests",
    "be a good girl",
    "i love you",
    "i love myself",
    "there is beauty all around me",
    "my life is abundant",
    "i love cherries",
    "do you still love me",
    "do you even love me"
];

export default thoughts;